### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mharisjamal** [mehdibenjid/Siamese-Network-PyTorch#1]
The dataset you mentioned is not with format as used in code. Would you mind telling the dataset you used in code!

**Comment by mehdibenjid** [comment]
Hi,

You're completely right, I will update the files. Thanks for the remark


Le ven. 8 nov. 2024 à 20:02, Muhammad Haris ***@***.***> a
écrit :

**Comment by mehdibenjid** [comment]
Data folder added. Let me know if you have any further questions. : )

**Comment by mharisjamal** [comment]
Thank you. I appreciate that!
